apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  labels:
    app: myapp
    key: rep
spec:
  replicas: 2
  selector:
    matchLabels:
      key: rep
  template:
    metadata:
      labels:
        key: rep
    spec:
      containers:
        - name: myapp
          image: nginx
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: myjob
  namespace: default
spec:
  selector:
    app: myapp
    key: rep
  type: ClusterIP
  ports:
  - name: myjob
    protocol: TCP
    port: 80
    targetPort: 5000
    nodePort: 30001
---

