apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense
  region: us-east-1

managedNodeGroups:
  - name: expense
    instanceType: t3.micro
    desiredCapacity: 3
    spot: true
    # availabilityZones:
    # - us-east-1f